### PR TITLE
Allow `psr/log` `^1.0 || ^2.0 || ^3.0`

### PR DESCRIPTION
**Pull request by ruudk**
Needed for Symfony 6.0

### CODE REVIEW

**Comment by rosstuck** [comment]
Think this might want to be against the tactician-v1 branch instead? master is currently all the v2 stuff that I haven't released.

**Comment by ruudk** [comment]
Oops! Will fix it now

**Comment by ruudk** [comment]
Weird, somehow v1 is already fixed, but master is off... that's why I was confused.

Turns out https://packagist.org/packages/league/tactician-logger#v0.11.0 is already compatible with v1/2/3. Might be good to merge this to master then?

**Comment by rosstuck** [comment]
Right you are, my apologies. When I get a chance to do anything with this now, it's X branches over Y packages so entirely my mistake. Thanks for sending this in!

**Pull request merged**
